### ISSUE TITLE
Increase memory_limit	 

### ISSUE THREAD

**Issue by vamsiikrishna** [jakzal/phpqa#1]
Hi,
Thanks for creating this project ! 
while running phpstan on a medium project , I am running into memory exhausted issue. 
``` Fatal error: Allowed memory size of xxxxxxxx bytes exhausted (tried to allocate x bytes) in phar:///usr/local/bin/phpstan/src/File/FileHelper.php on line 49 ```

can you please consider setting the default value to -1 ?

Edit : Just to make sure that my system's RAM is not completely exhausted and that it's not already to set to -1

``` # sudo docker run -it --rm jakzal/phpqa php -i | grep memory_limit ```
memory_limit => 128M => 128M

**Comment by jakzal** [comment]
Thanks for reporting. I just faced the same problem and pushed a fix.
