### ISSUE TITLE
missing image tags for 7.1

### ISSUE THREAD

**Issue by gimler** [jakzal/phpqa#105]
The following tags 1.14.2-php7.1 and 1.14.2-php7.1-alpine are missing on docker hub.

The last 7.1 release with minor number is 1.13.0-php7.1

**Comment by jakzal** [comment]
Thanks for reporting. There was a typo in build definitions which I now fixed.

I also triggered new build so missing tags should be available soon.

**Comment by jakzal** [comment]
php 7.1 tags are now available on docker hub.

<img width="941" alt="image" src="https://user-images.githubusercontent.com/190447/50375753-8e5e0500-05fa-11e9-8007-e1ae4397e289.png">
