### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by dkarlovi** [jakzal/phpqa#106]
Mentioned in #95, but here it is again. I might be missing something, but [don't see 7.3-related tags](https://hub.docker.com/r/jakzal/phpqa/tags)?

A Docker Hub issue?

**Comment by jakzal** [comment]
I think I might've forgotten to update docker hub's config...

**Comment by dkarlovi** [comment]
Can probably just add another set of tags for 7.3, we can fix it to automagically work with #94: it takes Git tag name + folder names from the project root and creates a Cartesian product to build & tag.

**Comment by jakzal** [comment]
What needs to be done for #94? I didn't have time to dig into it.

**Comment by dkarlovi** [comment]
Use a hooks script to tag a single build with all the tags we require.

**Comment by dkarlovi** [comment]
Since we now have 7.3, let's close this.
