### ISSUE TITLE
Explicitly set PHP's auto_globals_jit=0

### ISSUE THREAD

**Issue by dkarlovi** [jakzal/phpqa#115]
If set to `auto_globals_jit=1`, it breaks PHPUnit when running through `phpdbg`, https://github.com/sebastianbergmann/phpunit/issues/3514

See http://php.net/manual/en/ini.core.php#ini.auto-globals-jit

**Comment by dkarlovi** [comment]
[I've had to add it manually](https://github.com/dkarlovi/xezilaires/pull/62/files#diff-b67911656ef5d18c4ae36cb6741b7965R41) (and first to find the issue, of course :see_no_evil: ) so having it already be in the image makes sense to me.

**Comment by jakzal** [comment]
this is... weird :)

I'd try to avoid setting `auto_globals_jit` if possible.

**Comment by jakzal** [comment]
Is this only in alpine? see https://github.com/sebastianbergmann/phpunit/issues/3352#issuecomment-430629750

**Comment by dkarlovi** [comment]
Maybe the setting is different in Alpine and Debian? Maybe it's a bug in upstream Docker image we inherit?

**Comment by dkarlovi** [comment]
BTW since the image is meant for one-off CLI usage, I'd say we could still ensure this is disabled since the performance impact should be negligible, but the tools being broken isn't.

**Comment by jakzal** [comment]
Sure. I only would like to see if there's no other way to solve the problem.

**Comment by dkarlovi** [comment]
It's a PHPUnit issue, they don't seem interested in fixing it.

**Comment by dkarlovi** [comment]
Since it's beeing closed in both PHPUnit 7 & 8, closing here. Thanks for your voice in those issues. :+1:
