### ISSUE TITLE
Adding Exakat to phpqa

### ISSUE THREAD

**Issue by dseguy** [jakzal/phpqa#119]
I'd like to add Exakat to the phpqa suite. 

What is the prefered process ? Shall I first submit the installation to toolbox? 

I have a dockerfile for debian and another for alpine. PHP 7.0 to 7.3 are all OK to run exakat.

The main block I see is java and gremlin-server. Is there a prefered way to have available? 
They are needed for processing the report, but are discarded after running it : docker is good for that.

**Comment by jakzal** [comment]
Exakat seems like a very comprehensive tool. Due to its size and dependencies I think it deserves its own image though.

I'd still like to include it on the list in the README.

**Comment by jakzal** [comment]
Thank you for your suggestion!

I [included](https://github.com/jakzal/phpqa/commit/21eeeb3a8fe1f4bb468ec835b9ec5c67e8c64165) exakat on the list in the [More tools](https://github.com/jakzal/phpqa#more-tools) section. Soon I'll add more to that list.

**Comment by dseguy** [comment]
OK, I understand. There is already a debian image here : https://cloud.docker.com/u/exakat/repository/docker/exakat/exakat
