### ISSUE TITLE
Broken autoloader

### ISSUE THREAD

**Issue by ro0NL** [jakzal/phpqa#139]
_Im not aware of the autoloader complexity on anybody's side, so im starting here :) I think it's related to PHPstan isolation due this image._

composer.json requires symfony/dependency-injection, which on itself requires symfony/contracts

running `vendor/bin/phpstan` locally, `Symfony\Contracts\Service\ServiceProviderInterface` points to `/app/vendor/symfony/contracts/Service/ServiceSubscriberInterface.php` :+1: 

running `phpstan` globally, it points to `/tools/.composer/vendor-bin/phpstan/vendor/symfony/contracts/Service/ServiceSubscriberInterface.php` :-1: 

I discovered it as the versions are incompatible, and as such the build broke: https://travis-ci.org/msgphp/msgphp/jobs/513370572#L305

**Comment by jakzal** [comment]
Isn't this the known problem with any tool that has dependencies common with a project it's used in? Like it's the reason why Symfony runs phpunit in a special way to remove the yaml dependency.

**Comment by ro0NL** [comment]
maybe :) im not sure which behavior i relied on actually :sweat_smile: or what exactly happened.

adding symfony/contracts as a root-requirement doesnt help, but in general this is super tricky :( so im thinking to keep a local composer.phpstan.json instead.

composer-bin-plugin is at fault here, isnt it?

**Comment by ro0NL** [comment]
why exactly are we using `composer-bin-plugin` ? :D for the toolbox we could simply install each tool in an isolated directory, no? That's 100% safe.

**Comment by ro0NL** [comment]
Actually the difference is due `phpstan/phpstan` vs. `phpstan/phpstan-shim`. Using the root vendor directory is used. Respectively

```
/app/var/isolated/vendor/symfony/contracts/Service/ServiceSubscriberInterface.php

vs.

/app/vendor/symfony/contracts/Service/ServiceSubscriberInterface.php
```

Now using the toolbox extension's at `` produces

```
Class PHPStan\Rules\Deprecations\AccessDeprecatedPropertyRule used in service 'rules.57' not found
```

This i can locally solve using

```json
    "autoload": {
        "classmap": [
            "/tools/.composer/vendor-bin/phpstan/vendor/phpstan/phpstan-deprecation-rules/src/",
            "/tools/.composer/vendor-bin/phpstan/vendor/phpstan/phpstan-phpunit/src/"
        ]
    }
```

**Comment by jakzal** [comment]
> why exactly are we using composer-bin-plugin 

To prevent issues like this one 😂

**Comment by ro0NL** [comment]
closing for now, seems like the deps solved itself :)
