### ISSUE TITLE
Package PlantUML missing to generate uml with dephpend

### ISSUE THREAD

**Issue by garygitton** [jakzal/phpqa#168]
Using this command
```shell
docker run -it --rm -v ${PWD}:/project -w /project jakzal/phpqa:alpine dephpend uml --output=uml.png ./
```
I get this error
```shell
Something went wrong, this shouldn't happen. Please take a minute and report this issue: https://github.com/mihaeu/dephpend/issues

PlantUML installation not found.

[phar:///tools/dephpend/src/OS/PlantUmlWrapper.php at line 57]
```

So I guess, PlantUML should be installed directly in the docker image to be able to generate uml graph.

**Comment by frank-sons** [comment]
This would really be nice, as these diagrams can be easily used to find cross dependencies in your code

**Comment by jakzal** [comment]
PlantUML is distributed as a jar. We'd need to include a java distribution as well. Isn't it too much?

**Comment by garygitton** [comment]
Hello :) Tahnk you for coming back on this error.
Could we have an env variable `INSTALL_PLANT_UML` which would have as default value false.
If true the plant uml is installed by the entrypoint.

**Comment by jakzal** [comment]
That would slow down each run significantly. 

I haven't tested it, but if your really want to do it you could mount the entrypoint to override it (or use `--entrypoint` option).

**Comment by jakzal** [comment]
Another option is of course to extend this image.
