### ISSUE TITLE
Add xdebug

### ISSUE THREAD

**Issue by dkarlovi** [jakzal/phpqa#18]
If you want to run coverage tools, you need xdebug. Might want to disable by default.

**Comment by jakzal** [comment]
Loading xdebug by default isn't desired for performance reasons. Loading xdebug, even without enabling it, hurts performance.

We could indeed ship it by default, but disabled.

What would be required to enable it though? You'd either need to:
* run the container, enable the extension manually, use it - it would be gone next time you run the container, or
* create your own image that would enable the extension - you'd only save on having to compile the extension

So, I'm not sure if it's worth it. What do you think?

**Comment by jakzal** [comment]
Another option would be tag xdebug-enabled images separately. We'd have 1.5.0, 1.5.0-xdebug, latest, xdebug, alpine, alpine-debug.

**Comment by dkarlovi** [comment]
What I do in my version of this idea is to have a environment variable with which I [control whether I leave xdebug config in-place or not](https://github.com/dkarlovi/php-toolbox/blob/master/sys/docker-entrypoint.sh#L3-L5). It's not really elegant, but it works as expected.

Also, @sstok pointed out `php-dbg` is able to collect coverage data in https://github.com/rollerworks/search/pull/194#discussion-diff-150610187R17 so maybe that's a better direction?

**Comment by jakzal** [comment]
I just realised you can already get the code coverage as phpdbg is already available:

```
phpqa phpdbg -qrr ./phpunit --coverage-text src/Symfony/Component/Dotenv/Tests/
```

** phpqa is an alias to the docker command and ./phpunit is the path to phpunit

**Comment by dkarlovi** [comment]
Good enough for me, closing.
