### ISSUE TITLE
Pcov for faster code coverage

### ISSUE THREAD

**Issue by dkarlovi** [jakzal/phpqa#183]
https://github.com/krakjoe/pcov

**Comment by Guite** [comment]
:+1: 
Possible setup in alpine: `pecl install pcov && docker-php-ext-enable pcov`

**Comment by jakzal** [comment]
How much faster? :D

**Comment by Guite** [comment]
> How much faster? :D

https://dev.to/swashata/setup-php-pcov-for-5-times-faster-phpunit-code-coverage-3d9c

;-)

**Comment by maks-rafalko** [comment]
I second this. Today we had [one more weird bug](https://github.com/infection/infection/issues/1038) with Infection + phpdbg. It just doesn't work for some unknown reason, while works with PHP itself (including xdebug & pcov).

Here is a quote from Jow Watking (author of `phpdbg`) about another issue that I spend a week of debugging with:

https://github.com/infection/infection/pull/622#issuecomment-462159182

> I did try to reproduce the issue, I wrote the core of phpdbg and am intimately familiar with it, I'm also aware that aside from mistakes in coverage (which I did not write) it has bugs that may also be effecting you and are stopping me from even doing a full run locally, there's some problem with too many open file handles, class not found and such, this all seems to be connected to your current headache ...
>
> Jow Watking (krakjoe)

Let's discourage people from using `phpdbg`. For coverage, we should (must) use `pcov` from the same author, which is [extremely faster](https://twitter.com/infection_php/status/1171520500821938177?s=20).

> To give you some numbers, PHPUnit run takes 1.3 minute with `pcov` vs 4 minutes with Xdebug with xdebug-filter
