### ISSUE TITLE
Add yaml, xliff and twig lint from Symfony util

### ISSUE THREAD

**Issue by vsilvestre-accenture** [jakzal/phpqa#195]

**Comment by jakzal** [comment]
Are these distributed as standalone tools.

**Comment by vsilvestre-accenture** [comment]
> Are these distributed as standalone tools.

Sorry for lack of activity !
I know they are provided in symfony twig bridge, in yaml component and symfony core. Maybe they need some extra work to be used standalone, but I think yaml at least is usable out of the box
