### ISSUE TITLE
1.30 failing as a Github action (1.29 works)

### ISSUE THREAD

**Issue by dkarlovi** [jakzal/phpqa#200]
I have this issue in my build after bumping to 1.30:

```
Generating code coverage report in PHPUnit XML format ... done
sh -c "  phpdbg -qrr /tools/infection run --verbose --show-mutations --no-interaction --only-covered --coverage var/ --min-msi=100 --min-covered-msi=100 --threads 4"
zend_mm_heap corrupted
```

Check the build output [here](https://github.com/dkarlovi/xezilaires/pull/97/checks?check_run_id=435854447#step:6:48) (open it manually, Github's UI seems to not properly expand the output fully currently), the only thing that changed is the image version. It works locally (as did the previous version).

**Comment by jakzal** [comment]
Infection was updated (0.15.0 -> 0.15.1), but it seems to have been a small update.

Perhaps an update to PHP makes phpdbg to crash?

**Comment by dkarlovi** [comment]
I've just checked it with @maks-rafalko and it seems to be caused by Infection 0.15.1 indeed, I've pulled 0.15.0 directly into image 1.30 and it [worked](https://github.com/dkarlovi/xezilaires/actions/runs/36952358/workflow), but bumping the downloaded PHAR to 0.15.1 into the same image [failed](https://github.com/dkarlovi/xezilaires/actions/runs/36954068/workflow) as the built-in one too.

**Comment by dkarlovi** [comment]
So I guess we can either close here and move the issue to Infection's repo or keep this open to keep track of it once the patch is released. WDYT @jakzal @maks-rafalko?

**Comment by maks-rafalko** [comment]
I'm ok opening it on Infection repo, since it's not a phpqa's issue.

**Comment by dkarlovi** [comment]
Alright, closing here since there's nothing PHPQA can do.

**Comment by dkarlovi** [comment]
It seems to be a combination of PHPDBG and something 0.15.1 started doing different.

**Comment by jakzal** [comment]
Do we need to start getting worried phpdbg won't work nicely with infection anymore?

**Comment by dkarlovi** [comment]
All the more reason to move for #183. :angel:
