### ISSUE TITLE
Is it possible to load custom tool versions?

### ISSUE THREAD

**Issue by dizzersee** [jakzal/phpqa#206]
I know from reading the docs of Toolbox that it is possible to [load custom tool definitions](https://github.com/jakzal/toolbox/#tools-definitions):
e.g. `./toolbox list-tools --tools path/to/file1.json --tools path/to/file2.json`

Is it possible to start and use Phpqa with a custom tools definitions file? I would like to install custom verions of some tools.

**Comment by jakzal** [comment]
Yes, either customise the image (see https://github.com/jakzal/phpqa#customising-the-image) or create a totally new one.
