### ISSUE TITLE
Psalm tool is broken

### ISSUE THREAD

**Issue by githoober** [jakzal/phpqa#213]
With the following psalm.xml in place
```
<\?xml version="1.0"\?>
<psalm
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        totallyTyped="false"
        errorLevel="4"
        resolveFromConfigFile="true"
        xmlns="https://getpsalm.org/schema/config"
        xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
        errorBaseline="build/psalm/baseline.xml"
>
    <projectFiles>
        <directory name="src"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>
</psalm>
```

and running 
`sudo docker run --init -it --rm -v "$(pwd):/project" -v "$(pwd)/tmp-phpqa:/tmp" -w /project jakzal/phpqa psalm analyse`

I am getting the following error:

`Problem parsing /project/psalm.xml:
  Error on line 10:
    Element '{https://getpsalm.org/schema/config}psalm', attribute 'errorLevel': The attribute 'errorLevel' is not allowed.
`
The schema at https://psalm.dev/schema/config has the attribute 'errorLevel' for the element 'psalm' but it seems that this attribute was renamed from 'level' to 'errorLevel' two months ago: https://github.com/vimeo/psalm/commit/320f3ec863b04846f1496031f9a8f7412e6bf53c

At this point, this appear to be an issue with the toolbox instead.

**Comment by muglug** [comment]
What version of Psalm are you using? I think you’re just a few versions behind

**Comment by githoober** [comment]
@muglug Doesn't jakzal/phpqa use the psalm tool provided by jakzal/toolbox? 

Anyway, not the error is different:

```
Fatal error: Declaration of _HumbugBox9af19da13138\Psalm\Internal\Provider\ReturnTypeProvider\ArrayChunkReturnTypeProvider::getFunctionReturnType(_HumbugBox9af19da13138\Psalm\StatementsSource $statements_source, string $function_id, array $call_args, _HumbugBox9af19da13138\Psalm\Context $context, _HumbugBox9af19da13138\Psalm\CodeLocation $code_location) must be compatible with Psalm\Plugin\Hook\FunctionReturnTypeProviderInterface::getFunctionReturnType(Psalm\StatementsSource $statements_source, string $function_id, array $call_args, Psalm\Context $context, Psalm\CodeLocation $code_location) in phar:///tools/psalm/src/Psalm/Internal/Provider/ReturnTypeProvider/ArrayChunkReturnTypeProvider.php on line 18
```

**Comment by jakzal** [comment]
@githoober can you make sure you pulled the latest image with `docker pull jakzal/phpqa` ?

Also, your xml header seems to be invalid. It should be `<?xml version="1.0"?>` instead of `<\?xml version="1.0"\?>`.

**Comment by jakzal** [comment]
@githoober do you still have this problem? 

Can you show me the output of the following command?

```docker images jakzal/phpqa```

**Comment by jakzal** [comment]
I'm gonna close due to lack of feedback. I expect an old version of the image was used. Let me know otherwise.

**Comment by BenjaminHoegh** [comment]
i do have the same issue on composer 

using `mickaelandrieu/psalm-ga@v1.1`

```
 Element '{https://getpsalm.org/schema/config}psalm', attribute 'errorLevel': The attribute 'errorLevel' is not allowed.
```
