### ISSUE TITLE
image 1.38.0-php7.3-alpine wasn't deployed

### ISSUE THREAD

**Issue by fizzka** [jakzal/phpqa#226]
$ docker pull jakzal/phpqa:1.38.0-php7.3-alpine                                                                                                                               
Error response from daemon: manifest for jakzal/phpqa:1.38.0-php7.3-alpine not found: manifest unknown: manifest unknown

though, 1.38-php7.3-alpine is present

**Comment by jakzal** [comment]
Thanks for letting us know. Some builds have failed on docker hub and were not retried. 

`1.38-php7.3-alpine` should be present now. There were few other missing, which are currently being built.

**Comment by jakzal** [comment]
All the latest tags were now regenerated:


```
$ http GET 'https://registry.hub.docker.com/v1/repositories/jakzal/phpqa/tags' | jq '.[] | select(.name|test("1.38")) | .name' | sort
"1.38"
"1.38-alpine"
"1.38-php7.2"
"1.38-php7.2-alpine"
"1.38-php7.3"
"1.38-php7.3-alpine"
"1.38-php7.4"
"1.38-php7.4-alpine"
"1.38.0"
"1.38.0-alpine"
"1.38.0-php7.2"
"1.38.0-php7.2-alpine"
"1.38.0-php7.3"
"1.38.0-php7.3-alpine"
"1.38.0-php7.4"
"1.38.0-php7.4-alpine"
```
