### ISSUE TITLE
How to use `analyze serve`

### ISSUE THREAD

**Issue by iainfogg** [jakzal/phpqa#229]
Hi, I've run `analyze` successfully, but I've not figured out how to get `analyze serve` to allow me to connect to its web server from my host.

I've tried various Docker parameters like `-p 8080:8080`, `--expose 8080`, I've tried making my own `Dockerfile` with `EXPOSE 8080` in it etc. and can never connect from my local browser using `http://localhost:8080/` or `http://127.0.0.1:8080/`.

Does anyone know what the correct way is to access `analyze`'s web server is from the Docker host?

By the way, I did try `exec`ing into the running container and running `curl http://localhost:8080` and successfully got some HTML outputted into the terminal, so the server is running.

If I run `curl http://127.0.0.1:8080` from my host, I get the error `curl: (56) Recv failure: Connection reset by peer` (I get a different error if I pick a different port, so it is getting through in some way).

The web server never outputs anything while running except for when I `exec`d into the running container and did a `curl` from there.

**Comment by jakzal** [comment]
You need to tell the tool to listen on any host, as localhost on the container is not your localhost ;)

```
docker run -it --rm -v $(pwd):/project -w /project -p 8080:8080 jakzal/phpqa:alpine analyze serve --hostname 0.0.0.0
```

**Comment by jakzal** [comment]
If you use the `--rm` flag, fs is not persisted between runs, so you'll need to make sure you generate metrics and serve them in the same container:

<img width="897" alt="image" src="https://user-images.githubusercontent.com/190447/84567483-d6ce2d00-ad70-11ea-94c8-a35c09d6f434.png">

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/190447/84567486-de8dd180-ad70-11ea-9db7-ef7999a0e995.png">

**Comment by iainfogg** [comment]
Great, thanks a lot @jakzal - all working now!
