### ISSUE TITLE
Composer version 2.0.2 in phpqa:php7.3-alpine

### ISSUE THREAD

**Issue by radist** [jakzal/phpqa#252]
```
$ docker run jakzal/phpqa:php7.3-alpine composer -V
Composer version 2.0.2 2020-10-25 23:03:59
```

```
$ docker run composer:1.9 -V
Composer version 1.9.3 2020-02-04 12:58:49
```

**Comment by jakzal** [comment]
composer self-update is run during the build, so looks like it allowed to jump from 1 to 2

**Comment by orangevinz** [comment]
Same on the php7.4, breaking my CI/CD
Is there any workaround to force the composer version ?

**Comment by jakzal** [comment]
@orangevinz how did it break? 

If it breaks people's CIs we should find a way to downgrade composer, i.e.: `composer self-update --1`

**Comment by orangevinz** [comment]
I've been using it with hirak/prestissimo so I had this error:
```
[InvalidArgumentException]                                                                                                           
  Package hirak/prestissimo at version  has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version  
```
It seems this package is no longer usefull with composer 2 as it's mentionned here :+1:  https://github.com/hirak/prestissimo/issues/233

Anyway, I'll try to migrate my obsolete package to supports composer 2.0 and we'll be done I guess ;-)

**Comment by jakzal** [comment]
Yes, prestissimo is redundant with Composer 2. Just uninstall it ;)

I have downgraded Composer to the latest v1 as the upgrade wasn't expected nor planned. 

I suggest you lock yourself to one of 1.41.4 tags (i.e. 1.41.4-php7.3-alpine). Images are currently being built. It might take a few hours...

One of the next minor versions should get Composer 2 again.
