### ISSUE TITLE
Enable some widely used extensions

### ISSUE THREAD

**Issue by kocsismate** [jakzal/phpqa#26]
Hey,

I use your image for running PHPStan for one of my project. As I declared some global functions in a bootstrap file of the project, I must pass the `bootstrap` configuration option for PHPStan. The problem is that the `gettext` extension is used during bootstrap, so the analysis fails with a fatal error because the `bindtextdomain` function can't be found.

That's why I'd like to ask you to enable let's say the `gettext` and `intl` and maybe other widely used extensions like `phpredis`, `imagick` and `curl`.

**Comment by sstok** [comment]
You can create your own Docker image by extending this one 👍
That's why I did 

https://github.com/park-manager/park-manager/blob/master/docker/Dockerfile-qa
https://github.com/park-manager/park-manager/blob/master/docker/Dockerfile-qa

**Comment by kocsismate** [comment]
Yeah, I just wanted to avoid creating my own image.

In my opinion, enabling the most basic PHP extensions in phpqa does no harm, yet really easy to do and benefits almost all the users of PHPStan. So I think doing so is worth its price.

**Comment by jakzal** [comment]
I'm up for including extensions that are absolutely required by tools bundled with the image (i.e. a tool wouldn't work without it), but against extensions that are your project specific (like phpredis). In the second case creating your own image based on this one is the way to go as @sstok suggested. We can't satisfy all the setups out there.

**Comment by kocsismate** [comment]
Ok, I can understand your point of you. Thanks for the clarification. I'm closing the issue.
