### ISSUE TITLE
psalm 4.2.1 fails in phpqa 1.43.0

### ISSUE THREAD

**Issue by fizzka** [jakzal/phpqa#263]
docker run jakzal/phpqa:1.43.0-php7.4-alpine psalm
```
Psalm 4.2.1@ea9cb72143b77e7520c52fa37290bd8d8bc88fd9
Fatal error: Could not create cache directory: //.cache/psalm/5733b69be4963fd578e82e5fa92a3d5d6e73a093 in phar:///tools/psalm/src/Psalm/Config.php on line 688
...
```

**Comment by jakzal** [comment]
Do you know if the previous version is fine? i.e. v1.42.1
 
The only change in 1.43.0 is we started using Composer 2.

**Comment by fizzka** [comment]
same error on 1.42.1

**Comment by jakzal** [comment]
I think you need to change the working directory. I can't reproduce your issue even if I run the command you run: `docker run jakzal/phpqa:1.43.0-php7.4-alpine psalm`.


```
$ docker run -it --rm jakzal/phpqa:1.43.0-php7.4-alpine psalm
Could not locate a config XML file in path //. Have you run 'psalm --init' ?
```

I usually mount the project directory as a volume:

```
docker run -it --rm -v $(pwd):/app -w /app jakzal/phpqa:1.43.0-php7.4-alpine psalm
Scanning files...
Analyzing files...
```

**Comment by fizzka** [comment]
sorry, it was a problem with user&group
