### ISSUE TITLE
php-cs-fixer: not found

### ISSUE THREAD

**Issue by admiral2** [jakzal/phpqa#267]
Docker image: jakzal/phpqa:latest
Cmd line:
```
docker pull jakzal/phpqa:latest
docker run -v C:\xampp\htdocs\:/project -w /project --rm jakzal/phpqa:latest php-cs-fixer --diff --dry-run -v fix . 
```
Output: /entrypoint.sh: 6: exec: php-cs-fixer: not found

9 november 2020 all work fine

**Comment by jakzal** [comment]
php-cs-fixer is not available on PHP 8 yet. You'll need to use one of the older PHP versions.
