### ISSUE TITLE
ecs.phar symlink broken in latest php7.4-alpine

### ISSUE THREAD

**Issue by j13k** [jakzal/phpqa#269]
I've found that the `/tools` symlink for `ecs.phar` seems to be broken.

From a `docker run -it --rm jakzal/phpqa:php7.4-alpine /bin/sh` session, it can be seen that the symlink target no longer exists:

```
/ # ls -l /tools/ecs.phar
lrwxrwxrwx    1 root     root            53 Dec 20 15:14 /tools/ecs.phar -> /tools/.composer/vendor-bin/tools/vendor/bin/ecs.phar
/ # ls -l /tools/.composer/vendor-bin/tools/vendor/bin/ecs.phar
ls: /tools/.composer/vendor-bin/tools/vendor/bin/ecs.phar: No such file or directory
```

Thanks for the great project - really useful for PHP QA and CI.

**Comment by jakzal** [comment]
Thanks for reporting! 

I'm not sure why's there a link to ecs.phar to be honest. I think it might've been removed from EasyCodingStandard at some point.

Let's remove it, please use `ecs` instead: https://github.com/jakzal/toolbox/pull/319
