### ISSUE TITLE
Removed packages discussion

### ISSUE THREAD

**Issue by benr77** [jakzal/phpqa#276]
First of all thanks for such an awesome package. Much appreciated.

Is there a location discussing the rationale behind the removal of certain packages? For example I see `sensiolabs/security-checker` has been removed - it's specifically mentioned in the readme - but why was it removed?

Generally, I would want stability from this package if I'm going to build my tooling around it, it would be good if certain tools were not removed without proper notice and justification etc.

Maybe this is just a documentation issue - I'm happy to help if I can be of use.

**Comment by jakzal** [comment]
[security-checker](https://github.com/sensiolabs/security-checker) has been phased out:

> WARNING: Don't use this piece of software anymore as the underlying web service will stop working at the end of January 2021. Instead, use the Open-Source CLI tool that does the same locally, or use the Symfony CLI tool.

It's no longer possible to download the phar and my builds started to fail. Out of the blue :) Sorry, I'd normally mention why the package was dropped in the release notes. I was in a hurry today and didn't do it this time.

`local-php-security-checker` is a replacement. 

If you have any suggestions on how to improve the process, I'll be happy to take your ideas into consideration.

**Comment by jakzal** [comment]
Also, I don't usually remove tools unless they're abandoned or replaced by another tool.

**Comment by jakzal** [comment]
Finally, it's undocumented, but I always try to increase the minor version when a tool is added, removed, or its major version changes. It's done on the best effort basis, as, for example, I cannot prevent version changes for some packages (i.e. installed with composer as opposed to as phar).

**Comment by benr77** [comment]
Thank you for your detailed response. I suggest that there is no need to clutter up the README with this kind of information, but maybe having an (closed) Issue for each removal with a quick explanation would be good - that way it's easily searchable for anyone who's interested. And of course, if you want a pre-removal discussion an Issue also fits the bill.

With your strategy of incrementing the minor version number when any changes are made it's easy enough to pin our apps to a specific version so we don't get any surprises. 

Again, thanks for your efforts with this package.
