### ISSUE TITLE
ECS isn't included with PHP8 image

### ISSUE THREAD

**Issue by Pen-y-Fan** [jakzal/phpqa#286]
Thanks for this great resource!

I have just pulled the php8 image and tried to set up my dev environment, phpstan, ECS, PHPUnit etc. But was unable to get ECS to run, I searched the /tools/ directory and it is not installed. I manually installed it Ok:

```shell
cd /tools/.composer/
composer global require symplify/easy-coding-standard-prefixed
```

Note: The **prefixed** version is a phar to help with conflicts.

I pulled the PHP7.4 image and ECS was installed fine.

I read issue #283 , if there are compatibility issues with other PHP8 packages, would it be possible to add the known issues to the readme? 

I would be happy to update the README, if this will help. I can see the installed packages on PHP7.4 and PHP8, thanks to your helpful available packages list. I wish I had spotted that earlier :)

Possibly your output can be turned into a pivot table and create a summary:

| Package | php7.4 | php8.0 |
| :------ | :----- | :----- |
| analyze | &check; | | 
|behat| &check;| &check; |
|behat| &check;| &check; |
|behat| &check;| &check; |
|box| &check;| |
|behat| &check;| &check; |
|box| &check;| |
|box-legacy| &check;| &check; |
|churn| &check;| &check; |
|composer| &check;| &check; |
|composer-bin-plugin| &check;| &check; |
|composer-normalize| &check;| &check; |
|composer-unused| &check;| &check; |
|dephpend| &check;| &check; |
|deprecation-detector| &check;| &check; |
|deptrac| &check;| &check; |
|diffFilter| &check;| |
|doctrine-psalm-plugin| &check;| |
|ecs| &check;| |
|infection| &check;| &check; |
|larastan| &check;| &check; |
|local-php-security-checker| &check;| &check; |
|parallel-lint| &check;| |
|paratest| &check;| |
|pdepend| &check;| &check; |
|phan| &check;| &check; |
|php-coupling-detector| &check;| |
|php-cs-fixer| &check;| &check; |
|php-formatter| &check;| |
|php-semver-checker| &check;| &check; |
|phpa| &check;| &check; |
|phpat| &check;| |
|phpbench| &check;| &check; |
|phpca| &check;| &check; |
|phpcb| &check;| &check; |
|phpcbf| &check;| &check; |
|phpcov| &check;| &check; |
|phpcpd| &check;| &check; |
|phpcs| &check;| &check; |
|phpda| &check;| &check; |
|phpdd| &check;| &check; |
|phpdoc-to-typehint| &check;| &check; |
|phpDocumentor| &check;| |
|phpinsights| &check;| |
|phplint| &check;| &check; |
|phploc| &check;| &check; |
|phpmd| &check;| &check; |
|phpmetrics| &check;| &check; |
|phpmnd| &check;| |
|phpspec| &check;| &check; |
|phpstan| &check;| &check; |
|phpstan-beberlei-assert| &check;| &check; |
|phpstan-deprecation-rules| &check;| &check; |
|phpstan-doctrine| &check;| &check; |
|phpstan-ergebnis-rules| &check;| &check; |
|phpstan-exception-rules| &check;| &check; |
|phpstan-phpunit| &check;| &check; |
|phpstan-strict-rules| &check;| &check; |
|phpstan-symfony| &check;| &check; |
|phpstan-webmozart-assert| &check;| &check; |
|phpunit| &check;| &check; |
|phpunit-5| &check;| |
|phpunit-7| &check;| |
|phpunit-8| &check;| &check; |
|psalm| &check;| &check; |
|psecio-parse| &check;| &check; |
|rector| &check;| |
|roave-backward-compatibility-check| &check;| |
|simple-phpunit| &check;| &check; |
|twig-lint| &check;| &check; |
|twigcs| &check;| &check; |
|yaml-lint| &check;| &check; |

**Comment by jakzal** [comment]
At the time of creating the PHP 8 image, ecs didn't support PHP 8. Let's see if it supports it now: https://github.com/jakzal/toolbox/pull/355

If you'd like to help, it might be a good idea to go through the [tools tagged with `exclude-php:8.0`](https://github.com/search?q=%22exclude-php%3A8.0%22+repo%3Ajakzal%2Ftoolbox+language%3AJSON&type=Code&ref=advsearch&l=JSON&l=) and verify if any of them started to support PHP 8 yet.

I like your idea with the table presentation of tools. You'd need to update the task that generates it here: https://github.com/jakzal/toolbox/blob/master/bin/devkit.php#L70-L89

**Comment by Pen-y-Fan** [comment]
Thanks for your reply and adding ecs looks successful 👍 

I've taken a look at the available tools writer. I'll create a PR shortly.

**Comment by Pen-y-Fan** [comment]
[jakzal/toolbox#356](https://github.com/jakzal/toolbox/pull/356) created. Thanks for your direction, I wouldn't have done it without your help. I think it looks brilliant 😀, it will help others, I hope you like it too.

**Comment by nealio82** [comment]
Off-topic, but... I'm fascinated by the mental image of a mountain sitting down in front of a computer to make a PR

**Comment by Pen-y-Fan** [comment]
@nealio82 , for me Pen y Fan is a local mountain, the image is taken at the summit. I chose it to be a challenge, something that is an achievable target.

**Comment by jakzal** [comment]
v1.52* and latest images are now being built. ecs will be available in these builds.

@Pen-y-Fan if you'd like to continue your great contributions, feel free to remove `exclude-php:8.0` tags for tools that caught up and support PHP 8.0 now ;)

**Comment by nealio82** [comment]
I love Pen-y-Fan. It was the first mountain I climbed (about 25 years ago), and the first one I dragged my wife up. We go back to it every-so-often as a favourite. The horseshoe ridge is a great extended route (and don't forget to detour to the diving board at Fan-y-Big - it's tougher but it's worth it). Incidentally, my avatar is from the summit of Snowdon.

**Comment by jakzal** [comment]
ecs is now part of php 8 images
