### ISSUE TITLE
Add bmitch/churn-php

### ISSUE THREAD

**Issue by madnight** [jakzal/phpqa#3]
https://github.com/bmitch/churn-php

**Comment by jakzal** [comment]
Looks like a good addition :+1:

**Comment by jakzal** [comment]
We'll need to wait for https://github.com/bmitch/churn-php/pull/78

**Comment by madnight** [comment]
bmitch/churn-php#78 is merged

**Comment by bmitch** [comment]
That feature is in `0.1.0`: https://github.com/bmitch/churn-php/tree/0.1.0

Let me know if you need anything else.

**Comment by madnight** [comment]
actually it is in the master branch right now
