### ISSUE TITLE
Psalm plugin usage not possible

### ISSUE THREAD

**Issue by gimler** [jakzal/phpqa#301]
It is not possible to install/use psalm plugins
https://packagist.org/?type=psalm-plugin

This is because psalm is installed via phar see also
https://psalm.dev/docs/running_psalm/installation/

**Comment by jakzal** [comment]
Which phpqa version have you tried?

Since v1.54.0 I think it should work fine.

See https://github.com/jakzal/toolbox/pull/252

**Comment by jakzal** [comment]
@gimler have you tried the latest version?

**Comment by jakzal** [comment]
Closing due to lack of feedback. Feel free to provide more information and reopen.
