### ISSUE TITLE
Did you remove the alpine amd64 images from the Docker Hub?

### ISSUE THREAD

**Issue by Trois-Six** [jakzal/phpqa#305]
Hello,

Since 15 hours ago, I can't pull the linux/amd64 version of jakzal/phpqa:php7.4-alpine?
Do you know what happened?

```bash
$ docker pull jakzal/phpqa:php7.4-alpine
php7.4-alpine: Pulling from jakzal/phpqa
no matching manifest for linux/amd64 in the manifest list entries
```

[EDIT]It seems that only the alpine based images do have this problem[/EDIT]

Thx,

Pierre

**Comment by jakzal** [comment]
That might've been caused by a failed build for multi-arch images. I'll tag a new release soon, so you could use a tagged image. Stay tuned...

**Comment by VBelozyorov** [comment]
FYI: I've had been succeeded with `php7.3-alpine` several minutes ago

**Comment by jakzal** [comment]
Everything should be fine again. I replaced registry based layer caching with a local one.

Thanks for reporting!
