### ISSUE TITLE
Entrypoint is missing

### ISSUE THREAD

**Issue by 5n00p4eg** [jakzal/phpqa#307]
`docker run --rm -v project_path:project_path -w project_path jakzal/phpqa:php8.0 composer install --no-interaction --no-scripts`
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/entrypoint.sh\": stat /entrypoint.sh: no such file or directory": unknown.`

Errors came after the last update, 15 May 2021.

**Comment by jakzal** [comment]
Looks like multi-platform builds are still causing problems :(

**Comment by jakzal** [comment]
Fixed in https://github.com/jakzal/phpqa/commit/8034af81a5a435c9d921a51d74bdffe6ebe3b583
