### ISSUE TITLE
Entrypoint is missing on alpine flavour

### ISSUE THREAD

**Issue by Jojolam44** [jakzal/phpqa#308]
Same as #307 but for alpine

docker run --rm -ti jakzal/phpqa:alpine
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/entrypoint.sh\": stat /entrypoint.sh: no such file or directory": unknown.

Digest: sha256:deb16401fb73dd0f25300e3cbdea9ee71edef23cb4d6173ba1eba63b24dacbe6

No problem with debian flavour.

**Comment by jakzal** [comment]
The same fix should've fixed all images. I just tried and it works fine. Let me know if you still have issues.
