### ISSUE TITLE
Entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by vimAndNano** [jakzal/phpqa#309]
`docker run -ti jakzal/phpqa:1.58-php7.4-alpine sh`
ERROR: Job failed (system failure): Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/entrypoint.sh": stat /entrypoint.sh: no such file or directory: unknown (exec.go:57:0s)

**Comment by jakzal** [comment]
Thanks for reporting. Should be working now.
