### ISSUE TITLE
Need to update Riak

### ISSUE THREAD

**Issue by craigharman** [jakzal/phpqa#31]
Currently get error: 

Fatal error: Cannot use Riak\Object as Object because 'Object' is a special class name in /project/vendor/doctrine/cache/lib/Doctrine/Common/Cache/RiakCache.php on line 25

When I run:

 docker run -it --rm -v $(pwd):/project -w /project jakzal/phpqa phpstan analyse .

**Comment by jakzal** [comment]
Looks like you need to update dependencies in your project.

**Comment by jakzal** [comment]
see https://github.com/doctrine/cache/issues/179 and https://github.com/doctrine/cache/issues/206

**Comment by jakzal** [comment]
I'm gonna close since I don't think the issue is related to this repo.

In case I'm wrong, please provide more details and we'll reopen.
