### ISSUE TITLE
phplint is missing from image jakzal/phpqa:php7.3

### ISSUE THREAD

**Issue by deminy** [jakzal/phpqa#323]
Test commands:

```bash
docker run --rm -v "$(pwd):/project" -w /project -i jakzal/phpqa:php7.2 phplint --version # Output: phplint 2.0.2
docker run --rm -v "$(pwd):/project" -w /project -i jakzal/phpqa:php7.3 phplint --version
docker run --rm -v "$(pwd):/project" -w /project -i jakzal/phpqa:php7.4 phplint --version # Output: phplint 3.0
```

The output:

```text
phplint 2.0.2
/entrypoint.sh: 6: exec: phplint: not found
phplint 3.0
```

**Comment by jakzal** [comment]
`phplint` dropped support for PHP 7.3. In fact they seem to have dropped support for PHP 7 completely, so you might expect it'll stop working in PHP 7.4 soon as well.

If you want to use `phplint` with PHP 7.3 you can use the `1.60.0-php7.3` tag, which is the latest PHP 7.3 tag phplint is still present on.
