### ISSUE TITLE
How did you make the update of tools like f.i. Rector?

### ISSUE THREAD

**Issue by cavo789** [jakzal/phpqa#324]
Hello and thank you for phpqa!

Is it possible to retrieve somewhere in your docs (if any) how you proceed for updating tools? 

I've just discovered phpqa and install it with `docker pull`.  By running `phpqa rector --version` I got the version `0.10.21`.

By running `composer require rector/rector --dev` in one of my project to get the very latest version then `vendor/bin/rector --version`, I got `25da77f059de1b8871789cce1eab46716ff5c5f8` (not really readable) but, in my `composer.json`, I can see the installed version is `0.12.x-dev`.

And this is normal I think, you can't follow each version of each tools so fast...  I'm neverthless well afraid about versions: by using phpqa, is there any risk to use very old versions of tools because (with all my respect) you've not yet find time to make the upgrade?

Can I rely on phpqa for tools that are often updated?

Many thanks.

**Comment by jakzal** [comment]
# rector version

By using the `--dev` composer flag you installed a development version of rector. phpqa only uses stable releases (unless no stable release is available).

Nevertheless, the latest stable release of rector is [0.12.5](https://packagist.org/packages/rector/rector). It appears that rector has dropped its [rector-prefixed](https://packagist.org/packages/rector/rector-prefixed) package that we use. `rector/rector-prefixed` was replaced by [rector/rector](https://packagist.org/packages/rector/rector).

For this reason, we need to update it in toolbox that's used to install packages on phpqa (fancy sending a PR? ;) ):

https://github.com/jakzal/toolbox/blob/415dc12f3ca5f8635d5fb78eab260781601ced72/resources/refactoring.json#L36

As soon as that's updated, a new toolbox release will be made and we'll also need to update this repository to use the new version of toolbox.

# image updates 

As for how often package versions are bumped in phpqa, that depends on the package. We use the latest stable version if possible. This means that each image will have the latest available version at the time of image creation.

* tags like `latest`, `debian`, `alpine`, `php8.0`, `php8.0-alpine` etc are updated **daily**
* tags like `1.61.0`, `1.61.0-php8.0`, `1.61.0-php8.0-alpine` are updated once, when the tag is created
* tags like `1.61`, `1.61-php8.0`, `1.61-php8.0-alpine` are updated each time the patch version of the image is bumped

We have automated creation of tags, and by now tested the setup, so nothing stops us from going one step further and start triggering new tags weekly.

**Comment by jakzal** [comment]
`jakzal/phpqa` [v1.61.1](https://github.com/jakzal/phpqa/releases/tag/v1.61.1) was just released with the latest rector available (0.12.5).
