### ISSUE TITLE
error php version in docker image tag

### ISSUE THREAD

**Issue by filoucrackeur** [jakzal/phpqa#340]
Hello team !

php8 is install instead of php7.4 in my image generated in Dockerfile with FROM jakzal/phpqa:php7.4-alpine

it's a bug ?

**Comment by filoucrackeur** [comment]
Hooo sorry 

i added 

RUN apk add composer and it install php8 :(

**Comment by filoucrackeur** [comment]
it's on error with composer

**Comment by jakzal** [comment]
@filoucrackeur composer should already be present on the image so you don't need to install it.

If you'd like to update it to the latest version just run:


```
composer self-update
```
