### ISSUE TITLE
Authorize Composer plugins in /tools/.composer/composer.json

### ISSUE THREAD

**Issue by dkarlovi** [jakzal/phpqa#347]
If using `composer normalize`, you get the Composer 2.2 prompt to allow it running, which is impossible since the file is read-only (in the image):

```
ergebnis/composer-normalize (installed globally) contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "ergebnis/composer-normalize" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y


                                                              
  [RuntimeException]                                          
  The file "/tools/.composer/composer.json" is not writable.  
                                                              

```

**Comment by jakzal** [comment]
@dkarlovi have you customised the image? I thought we still run as root 🤔

**Comment by dkarlovi** [comment]
I'm running it as local user to generate files with proper permissions.

Either way, the Composer plugins should be pre-approved since they're hand picked. It shouldn't ask the user to enable them even if they are root.

**Comment by jakzal** [comment]
See https://github.com/jakzal/toolbox/issues/415

**Comment by dkarlovi** [comment]
Closing since it's a duplicate of https://github.com/jakzal/toolbox/issues/415
