### ISSUE TITLE
Install NPM or Node

### ISSUE THREAD

**Issue by mreduar** [jakzal/phpqa#351]
I am using Bitbucket pipelines and would like to install `npm` to do an asset compilation before running unit tests and static code analysis.
I tried to do it, but `apt-get` is not available to run
![image](https://user-images.githubusercontent.com/22550119/156385179-d3ab6d63-57cb-47ab-9e95-49500c2c0e45.png)

Reading the documentation I think the best way to do this is to [Customize the Image](https://github.com/jakzal/phpqa/blob/master/docs/cookbook/customising-the-image.md), but I'm not sure if this is the right way. Plus I'm new to Docker and wouldn't know how to use the image I create in my pipelines.
Am I on the right way? Can I get an example of how I could install `npm`? Thank you in advance

**Comment by jakzal** [comment]
@mreduar `apt-get` is available on images based on `debian`. You seem to be using the `alpine` based image. 

Either use `apk` with `alpine`, or switch to one of the images based on `debian` (with `debian` in image name like `jakzal/phpqa:php8.1-debian` or `jakzal/phpqa:debian`). You'll find the list of tags on docker hub: https://hub.docker.com/r/jakzal/phpqa/tags
