### ISSUE TITLE
Running php8.1 triggers deprecation notices 

### ISSUE THREAD

**Issue by stefgosselin** [jakzal/phpqa#359]
There seems to be compatibility issues for most of the toolset on the 8.1 image.  Maybe it's the way I have it setup.

I have phpunit, rector, ecs and yaml-lint in the pipeline on php8.1-alpine ( tried debian, same issue):

> docker run --init -it --rm -v "$(pwd):/app" -v "$(pwd)/tmp-phpqa:/tmp" -w /app jakzal/phpqa:php8.1-alpine yaml-lint config/*.yml

Running yaml-lint:
```
Deprecated: Return type of HumbugBox3111\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///tools/.phive/phars/j13k/yaml-lint-1.1.4.phar/.box/src/RequirementCollection.php on line 12

Deprecated: Return type of HumbugBox3111\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///tools/.phive/phars/j13k/yaml-lint-1.1.4.phar/.box/src/RequirementCollection.php on line 16
yaml-lint 1.1.4, symfony/yaml v5.2.5: parsing config/catalog.yml [ OK ]
yaml-lint 1.1.4, symfony/yaml v5.2.5: parsing config/miza.yml [ OK ]
```

Running Ecs:

![image](https://user-images.githubusercontent.com/359041/169060265-1a509b0e-d637-4fac-bd08-fed60cfa757e.png)

Everything works, all would be perfect were it not for the deprecation warnings.

Is there a tweak possible to disable these deprecation messages?

**Comment by jakzal** [comment]
These warnings are coming from specific tools mostly because of their dependencies on Symfony components. You'll need to check with those projects as they're not within our control.
