### ISSUE TITLE
Nightly builds are always cached

### ISSUE THREAD

**Issue by ciaranmcnulty** [jakzal/phpqa#364]
`nightly.yml` doesn't populate `INSTALLATION_DATE` build argument as far as I can tell

**Comment by jakzal** [comment]
Currently, nightlies do not use the cache at all: 

https://github.com/jakzal/phpqa/blob/0abb4abcf58ef0afd79276cbe999f243f4009a06/.github/workflows/nightly-builds.yml#L17-L20
