### ISSUE TITLE
Is it possible to upgrade PHPMD?

### ISSUE THREAD

**Issue by cavo789** [jakzal/phpqa#368]
Hello

I encounter a problem with PHPMD (https://github.com/phpmd/phpmd/issues/853) and then, I see that the last released version is `2.12.0`(https://github.com/phpmd/phpmd/releases/tag/2.12.0).

When I run `docker run -it --rm -v $(pwd):/project -w /project -u 1000:1000 jakzal/phpqa:php8.1 phpmd --version` I get version `PHPMD 2.9.1snapshot202009232245`.

So, is it possible to upgrade PHPMD?

Thanks!

**Comment by jakzal** [comment]
We always install the latest version available version with phive (https://github.com/jakzal/toolbox/blob/ffeb0e2fa72e699da56dcfd122fbfa7bc6205b8d/resources/tools.json#L91).

Can you make sure you pulled the latest docker image with `docker pull jakzal/phpqa:php8.1`?

**Comment by cavo789** [comment]
Thanks for your answer.

I was pretty sure but running `docker pull` once more right now. Same result on my side.

```bash
❯ docker run -it --rm jakzal/phpqa:php8.1 phpmd --version
PHPMD 2.9.1snapshot202009232245
❯ docker pull jakzal/phpqa:php8.1
php8.1: Pulling from jakzal/phpqa
b85a868b505f: Already exists
78fdfd2598e0: Already exists
26769c8659f4: Already exists
0bd105fadbe3: Already exists
79256ca8bbc5: Pull complete
3ec46bea2d21: Pull complete
c05dff01c78f: Pull complete
09a9da0880df: Pull complete
2042311512ee: Pull complete
409036cad48a: Pull complete
499ec83f3c18: Pull complete
ac9d9c015b01: Pull complete
af9c79859762: Pull complete
ac8ecb020760: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:a6ec26ca2052f933ce8d29e3b2951fed09d42662706050c79770fbb9f6e57b37
Status: Downloaded newer image for jakzal/phpqa:php8.1
docker.io/jakzal/phpqa:php8.1
❯ docker run -it --rm jakzal/phpqa:php8.1 phpmd --version
PHPMD 2.9.1snapshot202009232245
```

Did you get version PHPMD 2.12 on your computer ?

I don't know phive: is it possible that something wasn't done by PHPMD developpers to make the latest version 2.12.0 available for phive?

**Comment by jakzal** [comment]
I will check later when I’m on my laptop. Is it possible that phpmd devs didn’t update the version string?

**Comment by jakzal** [comment]
Looks like phpmd stopped publishing the phar signature:

```
Phive 0.15.1 - Copyright (C) 2015-2022 by Arne Blankerts, Sebastian Heuer and Contributors
Fetching repository list
Downloading https://phar.io/data/repositories.xml
[WARNING] phpmd 2.12.0: No GPG Signature
[WARNING] phpmd 2.11.1: No GPG Signature
[WARNING] phpmd 2.11.0: No GPG Signature
[WARNING] phpmd 2.10.2: No GPG Signature
[WARNING] phpmd 2.10.1: No GPG Signature
[WARNING] phpmd 2.10.0: No GPG Signature
Downloading https://github.com/phpmd/phpmd/releases/download/2.9.1/phpmd.phar
Downloading https://github.com/phpmd/phpmd/releases/download/2.9.1/phpmd.phar.asc
Downloading key 0F9684B8B16B7AB0
Trying to connect to keys.openpgp.org (37.218.245.50)
Downloading https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0x0F9684B8B16B7AB0
Successfully downloaded key.

        Fingerprint: 3C68 40FC AFFB B059 F283 8A2C 0F96 84B8 B16B 7AB0

        PHPMD (PHP Mess Detector) <pgp@phpmd.org>

        Created: 2019-10-29

Linking /usr/local/bin/.phive/phars/phpmd-2.9.1.phar to /usr/local/bin/.phive/tmp/ee12aa71ce468d7b326c001e4d291579/phpmd
```

**Comment by cavo789** [comment]
Thanks for the Investigation !!!

**Comment by jakzal** [comment]
The phpmd team has fixed their release process. The latest phpmd release (2.12.0) is published with the key.

The latest phpqa release v1.77.3 now includes the latest phpmd (2.12.0).

Hope this helps.

**Comment by cavo789** [comment]
Great ! Many thanks !

As soon as I'll use phpmd back I'll give you feedback.

Right now phpmd was not part of our QA process.

**Comment by jakzal** [comment]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/190447/186971974-fcccb966-6481-4516-a4ff-339c93c47027.png">
