### ISSUE TITLE
Add model generator from json schema 

### ISSUE THREAD

**Issue by rvanlaak** [jakzal/phpqa#381]
Generating schemas often is part of the CI / QA pipelines, as integration with a frontend.

Would it be possible to add https://github.com/api-platform/schema-generator to the phpqa image?

**Comment by jakzal** [comment]
> schema is a command line tool part of [the API Platform framework](https://api-platform.com/) that instantly generates a set of PHP classes from [RDF](https://en.wikipedia.org/wiki/Resource_Description_Framework) vocabularies such as (but not limited to) [Schema.org](https://schema.org/) or [ActivityStreams](https://www.w3.org/TR/activitystreams-core/). Alternatively, it can generate PHP classes from an [OpenAPI](https://www.openapis.org/) documentation.

Sounds like something to be done during the development, rather than as a part of the CI. Or am I missing something?

**Comment by rvanlaak** [comment]
Partially. The use-case that I would like to explore is to generate PHP models of the JSON Schema of our Kafka event-bus schema. When engineers contribute to the schema, they do not have a PHP or any other runtime present. In other words, the PHP output models are a representation of the external interface as documented on the JSON Schema. This is why it would be great if the runtime would be available via a QA related image so Docker + a Makefile allows running it with a single CLI command like `$ make models` that would then build the PHP, TS and Python models from the schema. The model output does then need to be committed to the VCS, but the CI process should also render these models to see if there is a diff and thereby notify the engineer that they forgot to render the models. You can see it as a sort of "code style" QA check.

**Comment by jakzal** [comment]
I'm not entirely convinced, but if someone makes a PR to install their phar I'm going to merge it.

**Comment by dkarlovi** [comment]
I agree this doesn't seem to fit into the design goals of the image. :+1:
