### ISSUE TITLE
Releasing on merge to master?

### ISSUE THREAD

**Issue by ciaranmcnulty** [jakzal/phpqa#383]
This PR was merged to master https://github.com/jakzal/phpqa/pull/382

It seems to push `php8.0-alpine` _only_ to docker? I'm not sure we mean to be doing that?

**Comment by jakzal** [comment]
Merge to master should push all tags that do not contain the version number (i.e. do not contain `1.77.8`). Are you saying that's not what happened?

Looking at the tag "matrix" in the README.md, it's not exactly correct 🤔

**Comment by ciaranmcnulty** [comment]
Ah ok.
