### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by cavo789** [jakzal/phpqa#395]
Thank you for your amazing work with phpqa. I use it now in all my PHP CI pipelines since months with great pleasure and, too, locally in my git hooks and `make` commands.

I really love it.  

Thanks!

![download](https://user-images.githubusercontent.com/355999/210149216-646749c6-82a5-401d-bfca-226e9bc3bf63.jpg)

**Comment by jakzal** [comment]
Glad you find it useful! Cheers!
