### ISSUE TITLE
Composer on 1.86-PHP8.0-alpine is broken

### ISSUE THREAD

**Issue by dkarlovi** [jakzal/phpqa#402]
Try

```shell
docker run --rm --user "`id -u`:`id -g`" --volume "`pwd`:/project" --workdir /project jakzal/phpqa:1.86.0-php8.0-alpine composer normalize
```

Get 

```
In JsonFile.php line 198:
                                                          
  The file "/tools/.composer/auth.json" is not readable.  
```

These all work

```shell
# 8.0 Debian
docker run --rm --user "`id -u`:`id -g`" --volume "`pwd`:/project" --workdir /project jakzal/phpqa:1.86.0-php8.0 composer normalize

# 8.1
docker run --rm --user "`id -u`:`id -g`" --volume "`pwd`:/project" --workdir /project jakzal/phpqa:1.86.0-php8.1-alpine composer normalize

# 8.2
docker run --rm --user "`id -u`:`id -g`" --volume "`pwd`:/project" --workdir /project jakzal/phpqa:1.86.0-php8.2-alpine composer normalize
```

So just "8.0 Alpine" is broken, weird.

**Comment by dkarlovi** [comment]
@ciaranmcnulty IIRC you've worked on this last, maybe you have a hint why this specific combination wouldn't work?

**Comment by ciaranmcnulty** [comment]
No idea, does it work if you run as root?

**Comment by dkarlovi** [comment]
It does, yes, it seems the file only exists in this specific image and not in others for whatever reason. Maybe busted build cache? :thinking:

**Comment by jakzal** [comment]
I'll just make another release. Github was misbehaving yesterday.

**Comment by jakzal** [comment]
Triggered [v1.86.1](https://github.com/jakzal/phpqa/releases/tag/v1.86.1).

**Comment by jakzal** [comment]
Yesterday, the [1.86.0 build for alpine php 8.0](https://github.com/jakzal/phpqa/actions/runs/4515977883/jobs/7953854907) for whatever reason built stuff in the push phase (see timings): 

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/190447/227740156-98535b56-1d0d-47e8-8cd2-8323d0777e06.png">

This isn't expected. The push step is supposed to load what was previously built and push it to the registry. Like it happened in other builds, for example [1.86.0 for alpine PHP 8.1](https://github.com/jakzal/phpqa/actions/runs/4515977883/jobs/7953854987):

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/190447/227740267-b1e7542c-5eeb-47e5-a043-8347e812265e.png">

Thanks to this "glitch" the test command hasn't failed, but what was pushed wasn't necessarily what was verified?

**Comment by dkarlovi** [comment]
1.86.1 works as expected, closing. I guess a temporary glitch, but that's quite weird. Thanks @jakzal!
