### ISSUE TITLE
phpstan cannot index classes, method, vars ...  

### ISSUE THREAD

**Issue by hamdinh98** [jakzal/phpqa#407]
Hi there, 
I'm trying to execute phpstan in my gitlab ci pipeline, 
but phpstan cannot reference the classes, methods, vars ... et count them as **errors** 
i tried to provide a the vendor/autoload.php from the cache but the error still exist 
Is there anyone here who encountered this kind of issue? 

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - app/vendor/autoload.php
phpstan:
  image:
    name: jakzal/phpqa
  stage: lint
  tags:
    - docker
  script:
    #- ls -al
    - phpstan analyse ./app/src  --configuration=./app/phpstan.neon --memory-limit=-1
  only:
    refs:
      - branches
    changes:
      - "app/src/**/*"
  except:
    refs:
      - /^[1-9]{1,}\.[0-9x]{1,}$/`

**Comment by jakzal** [comment]
Hey, @hamdinh98 did you solve the problem or moved on to a different way of running phpstan?
