### ISSUE TITLE
Enabling opcache extension by default in CLI

### ISSUE THREAD

**Issue by dkarlovi** [jakzal/phpqa#409]
When running Psalm, it says

```
Install the opcache extension to make use of JIT on PHP 8.0+ for a 20%+ performance boost!
```

which makes sense, some heavy duty data shoveling would probably benefit from Opcache being installed and enabled in CLI.

WDYT?

Note: even if I enable it manually, it doesn't work

```
/project $ php -d zend_extension=opcache.so -d opcache.enable_cli=1 /tools/psalm | head 

Install the opcache extension to make use of JIT on PHP 8.0+ for a 20%+ performance boost!

Target PHP version: 8.2 (inferred from current PHP version).
Scanning files...
Analyzing files...
```

That might be related to Psalm's use of https://github.com/composer/xdebug-handler

**Comment by jakzal** [comment]
I don't see why not.

**Comment by dkarlovi** [comment]
@jakzal there we go, Psalm can now see the Opcache ext when running in the image.
