### ISSUE TITLE
Support php 8.2.11 ?

### ISSUE THREAD

**Issue by storiesontheway** [jakzal/phpqa#416]
Hello,
Thanks a lot for your work, i'm discovering your docker images and it looks amazing. 
But i can't make it work on my setup with frankenPHP because this one use the 8.2.11 version of PHP and i see that your php version is based on cli-buster at 8.2.7 (not updated since 4 months). 
Do you plan to use new versions of Debian soon? Like cli-bookworn that is using the latest PHP image.

Thanks :)

**Comment by storiesontheway** [comment]
sorry didn't not pay attention that the alpine image was up to date.

**Comment by jakzal** [comment]
No problem. Our images are based on the "official" PHP images. We take the latest available PHP version for both debian and alpine.
