### ISSUE TITLE
PHPMND in 1.95.1 fails to run successfully

### ISSUE THREAD

**Issue by joereynolds** [jakzal/phpqa#422]
Here's the error (though not really relevant for this codebase)

```
Fatal error: Uncaught Error: Call to undefined method PhpParser\ParserFactory::createForHostVersion() in /tools/.composer/vendor-bin/phpmnd/vendor/povils/phpmnd/src/Container.php:35
```

I can get around this by explicitly requiring v1.95.0 of the qa tools and using that instead.

To be clear

This fails (version 1.95.1)
`docker run --init -it --rm -v "$(pwd):/app" -v "$(pwd)/tmp-phpqa:/tmp" -w /app jakzal/phpqa:1.95.1-php8.2-alpine phpmnd app/`

This works (version 1.95.0)
`docker run --init -it --rm -v "$(pwd):/app" -v "$(pwd)/tmp-phpqa:/tmp" -w /app jakzal/phpqa:1.95.0-php8.2-alpine phpmnd app/`

Thank you :)

**Comment by jakzal** [comment]
@joereynolds are you sure this isn't a bug in phpmnd?
