### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by ostrolucky** [jakzal/phpqa#44]
Would be nice to schedule nightly build which builds new image with latest tools each day. I often find myself checking your releases, but I would feel being rude to ask you constantly to update it.

**Comment by jakzal** [comment]
Is it possible with the docker hub?

https://hub.docker.com/r/jakzal/phpqa/

**Comment by ostrolucky** [comment]
I think no, but should be possible with travis https://docs.travis-ci.com/user/cron-jobs/

**Comment by jakzal** [comment]
Only if travis could trigger a build on docker hub (something to check).

**Comment by jakzal** [comment]
It seems that the only way to trigger a docker hub build is to push something to the github repository.

**Comment by ostrolucky** [comment]
I'm not familiar how it's done with docker hub, but the way we do the pushing to AWS ECR is via docker CLI: 
```
docker build -t $TAG . && docker tag $TAG 12345.dkr.ecr.eu-west-1.amazonaws.com/$TAG && docker push 12345.dkr.ecr.eu-west-1.amazonaws.com/$TAG
```

Does that not work for dockerhub?

**Comment by jakzal** [comment]
That would mean I'm no longer building on docker hub, but now I'm building on travis. There's a risk it'll time out ;)

**Comment by ostrolucky** [comment]
Or maybe building on docker hub can be triggered by creating git tag? Which can be done in travis as well? But seems like plenty of guesswork is going on here. You know what, I'll try it out myself and will let you know how well it works :)

**Comment by jakzal** [comment]
> Or maybe building on docker hub can be triggered by creating git tag? 

This is already implemented. I just don't want to tag automatically ;)

**Comment by ostrolucky** [comment]
tag it, push it, delay, delete tag :boom:

**Comment by jakzal** [comment]
Implemented on a separate docker hub repo: https://hub.docker.com/r/jakzal/phpqa-nightly/
