### ISSUE TITLE
phpunit extension for phpstan

### ISSUE THREAD

**Issue by dinamic** [jakzal/phpqa#56]
Would it be possible to have the phpstan-phpunit extension automatically installed, please?

Here's an example from the [docs](https://github.com/phpstan/docker-image/blob/master/README.md):

```
FROM phpstan/phpstan:0.9
RUN apk --update --progress --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.7/community add \
    php7-dom \
    php7-xmlwriter \
    && composer global require phpstan/phpstan-phpunit
```

**Comment by jakzal** [comment]
Is `composer global require` the only way to install phpstan extensions?

**Comment by dinamic** [comment]
@jakzal, I guess it would depend on how the phpstan is installed really.

If you use require `composer require`, I would say you wouldn't need the dependency installed globally.

I can spend some time and do a PR, if this would help push the feature request faster :)

**Comment by dinamic** [comment]
Just noticed that the way this docker image works is to actually pull the already compiled PHAR file. Unfortunately, it does not have the extensions built-in, so if you are keen on having it as PHAR distro, maybe the only way would be to have it custom built by docker's automated build system.

[phpstan-compiler](https://github.com/fprochazka/phpstan-compiler) should be considered.
