### ISSUE TITLE
Add sensiolabs/security-checker

### ISSUE THREAD

**Issue by madnight** [jakzal/phpqa#6]
This tool detects vulnerabilities in composer dependencies https://github.com/sensiolabs/security-checker

**Comment by jakzal** [comment]
Sounds great, do you wanna send a PR?

**Comment by madnight** [comment]
I'm a bit lazy, but if you insist i would

**Comment by jakzal** [comment]
No worries, it's no biggie for me. I can do it.

**Comment by madnight** [comment]
https://github.com/jakzal/phpqa/pull/8
