### ISSUE TITLE
Place all the tools provided by the image in a common root, example /tools

### ISSUE THREAD

**Issue by dkarlovi** [jakzal/phpqa#91]
I'm experimenting with the "image as mounted sideloaded volume for another container" approach we talked about in Slack before. It works very well, with some issues.

Currently, the image keeps most of its tools within `/tools`, with PHARs being an exception. This somewhat makes problems for the approach since I'd need to mount multiple volumes to match the layout.

My proposal:

1. create a new folder `/tools/bin` and add it to `$PATH` (can be last to not mess with anything)
2. dump all PHARs there instead of `/usr/local/bin`
3. (optional, but highly desirable) add all other bin files here to as symlinks too (from `/tools/.composer/vendor/bin:/tools/QualityAnalyzer/bin:/tools/DesignPatternDetector/bin:/tools/EasyCodingStandard/bin`, probably `/usr/bin/composer` too)

This allows me to:

1. mount `/tools:/tools` (QA image => my container)
2. add `/tools/bin` to `$PATH` in my own container
3. just use the tools from within my running container as if they're natively there

The setup for this approach becomes MUCH more simple and the current behaviour is mostly kept.

WDYT?

**Comment by jakzal** [comment]
1. 👍 
2. 👍 
3. I'd put this on hold for now. Not sure how some of tools will behave when invoked via symlink.

**Comment by dkarlovi** [comment]
I knew you would mind 3), that's why I said

> can be last to not mess with anything

So, since `/tools/bin` would be the last one to be looked up, it **wouldn't** be used for the existing bin files. :smile: Everything would stay exactly like it is from their POV.

**Comment by dkarlovi** [comment]
Also, since the tools are usually registered as Composer's `bin`, they'd expect to be symlinked from `vendor/bin` anyway, most of them should work as-is.

**Comment by dkarlovi** [comment]
Migrated to https://github.com/jakzal/toolbox/issues/13
