### ISSUE TITLE
composer warns about missing unzip command

### ISSUE THREAD

**Issue by croensch** [jakzal/phpqa#96]
As i do `composer install` i get
> As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
> This may cause invalid reports of corrupted archives. Installing 'unzip' may remediate them.

Everything seems to work fine in my gitlab-ci experiment tough. So just for thought.

**Comment by jakzal** [comment]
Currently unzip is only installed for [the build time](https://github.com/jakzal/phpqa/blob/cc882e66c4f50f20a556d70c29b46b75fc4854b4/7.1/alpine/Dockerfile#L7) (BUILD_DEPS). We could keep it permently by moving it to [tool dependencies](https://github.com/jakzal/phpqa/blob/cc882e66c4f50f20a556d70c29b46b75fc4854b4/7.1/alpine/Dockerfile#L9) (TOOLS_DEPS).

**Comment by jakzal** [comment]
@croensch I included unzip in the final image now. Let me know how it goes :)
